- name: My first play
  hosts: conteiners
  vars:
    ansible_python_interpreter: /usr/bin/python3 
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
