- name: Teste de conexão
  hosts: servidor
  vars:
    ansible_python_interpreter: /usr/bin/python3 
  tasks:
   - name: Ping
     ansible.builtin.ping:

   - name: Status
     ansible.builtin.debug:
       msg: online
