- name: My first play
  hosts: conteiners
  vars:
    ansible_python_interpreter: /usr/bin/python3    
    ansible_ssh_private_key_file: /home/ansible/.ssh/id_ed25519.pub
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
