---
- hosts: conteiners
 vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  become: true
  tasks:
    - name: Print OS info
      ansible.builtin.package:
        name: vim
