- name: Instalando a ultima vesão dos pacotes Vim, nano, unzip, mtr,nmap,whois
  hosts: conteiners
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Instalando
    ansible.builtin.package:
      name:
        - vim
        - nano
        - whois
      state: latest

     ansible.builtin.debug:
       msg: Vim, nano, unzip, mtr,nmap,whois instalado com sucesso!!!
