- name: Instalando a ultima vesão dos pacotes Vim, nano, unzip, mtr,nmap,whois
  hosts: conteiners
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Instalando
    ansible.builtin.package:
      name:
        - vim
        - nano
        - whois
      state: latest

  - name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

  - name: Print the package facts
    ansible.builtin.debug:
      var: ansible_facts.packages
