---
- hosts: conteiners
  become: true
  tasks:
    - name: Instalando pacotes
      ansible.builtin.package:
        name: vim

      ansible.builtin.package:
        name: unzip

      ansible.builtin.package:
        name: whois
