- name: Instalando a ultima vesão dos pacotes Vim, nano, unzip, mtr,nmap,whois
  hosts: conteiners
  vars:
    ansible_python_interpreter: /usr/bin/python3 
    
  ansible.builtin.package:
    name:
      - vim
      - nano
      -whois
    state: latest
