- name: Instalando a ultima vesão dos pacotes Vim, nano, unzip, mtr,nmap,whois
  hosts: conteiners
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Instalando
    ansible.builtin.package:
      name:
        - vim
        - nano
        - whois
      state: latest

  - name: Check whether a package called foobar is installed
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages['vim'] | length }} versions of foobar are installed!"
  when: "'vim' in ansible_facts.packages"
